# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Track-Out' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for Track-Out
  pod 'GRDB.swift'
  target 'Track-OutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Track-OutUITests' do
    # Pods for testing
  end

end
